apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: ride-decentral-com-tls3
spec:
  secretName: ride-decentral-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: ridedecentral.com
  dnsNames:
    - ridedecentral.com
    - www.ridedecentral.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - ridedecentral.com
          - www.ridedecentral.com